Added background carousel
Girl-Code-It/Opportunity-Calendar-Frontend pull request #143
Opened 2021-03-25 04:48 UTC by drishtipeshwani

# Description

I have added an image carousel background where the post opportunity button is there.  In this manner - 
<img width="946" alt="2021-03-21 (2)" src="https://user-images.githubusercontent.com/65016769/112420212-daa4cc00-8d52-11eb-9a51-bdb9e5444520.png">

Fixed #106  (e.g. Fixed #8)

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-03-25 06:46 UTC, abdus requested changes

2021-03-25 06:46 UTC, abdus commented on src/Components/ViewOpportunity/index.js
> +
Syntax Error. 

```suggestion
        <h3
          style={{
            textAlign: 'center',
            marginTop: '220px',
            marginBottom: '200px',
          }}
        >
          Loading Opportunities if any...
        </h3>
```

2021-03-25 06:56 UTC, abdus commented
hey @drishtipeshwani, there are some syntax errors. Fixing them would make the check pass. I tried to fix it but could not.

2021-03-25 13:07 UTC, drishtipeshwani commented
> hey @drishtipeshwani, there are some syntax errors. Fixing them would make the check pass. I tried to fix it but could not.

I will check

2021-03-27 15:04 UTC, abdus commented
@drishtipeshwani let me know if you are still working on this PR.

2021-03-31 09:20 UTC, vaishali614 commented
@drishtipeshwani Due to your inactiveness, we're closing this PR.

2021-03-31 09:20 UTC, closed without merging