title correction
Girl-Code-It/Opportunity-Calendar-Frontend pull request #153
Opened 2021-03-26 08:00 UTC by saumyasrivastava08

#150

2021-03-26 08:25 UTC, Manvityagi requested changes

2021-03-26 08:25 UTC, Manvityagi commented on README.md
> +- If you are creating a new issue, then please also comment on it mentioning that You want to work on it.
Only the change respective to this issue shall be made in concerned PR.  This change was a part of your previous PR and is commited again.

2021-03-26 14:55 UTC, saumyasrivastava08 commented
done

2021-03-27 15:19 UTC, abdus commented
(from now on) when you create a new PR, mention the issue number in this format: `Fixes #ISSUE_NO`. GitHub will auto-link relevant issue to the PR.

2021-03-27 15:21 UTC, merged