Added animations
Girl-Code-It/Opportunity-Calendar-Frontend pull request #178
Opened 2021-04-02 07:11 UTC by sonalisonawane

# Description

The static Images of About us and banner sections are changed with animations illustrations images .

Fixed #167

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

I am attaching the images that I had added in this page, Actually if in case they looked static here but they are animated, you can go through this repo.:)
![AboutUs](https://user-images.githubusercontent.com/66239376/113390934-ffd2a500-9325-11eb-8ff6-8728139a874b.gif)

![banner](https://user-images.githubusercontent.com/66239376/113390903-f47f7980-9325-11eb-9e26-d4f3b0d19b52.gif)

2021-04-02 08:40 UTC, vaishali614 commented
@sonalisonawane These animated images look good. However, only About Us image seems relevant but not the Banner image. Please try some other illustration.

2021-04-02 10:22 UTC, abdus approved these changes
LGTM

2021-04-02 13:48 UTC, DeepanshiD commented
Hey @sonalisonawane this looks great, but don't stretch the first image just keep width as it is to 100%. Second one is perfect.

2021-04-02 15:49 UTC, vaishali614 commented
@sonalisonawane Please make the changes suggested by @DeepanshiD. Also, when you update your PR, do take the latest pull before doing so.

2021-04-03 04:39 UTC, sonalisonawane commented
> @sonalisonawane Please make the changes suggested by @DeepanshiD. Also, when you update your PR, do take the latest pull before doing so.

Do I have to add another one in Banner section ??

2021-04-03 05:24 UTC, sonalisonawane commented
> @sonalisonawane Please make the changes suggested by @DeepanshiD. Also, when you update your PR, do take the latest pull before doing so.

@vaishali614 , @DeepanshiD  mam ,
error: RPC failed; curl 18 transfer closed with outstanding read data remaining
fatal: the remote end hung up unexpectedly
fatal: the remote end hung up unexpectedly

this error is occurring while, pushing code.

2021-04-03 05:27 UTC, sonalisonawane commented
Done! I had change the banner image also fixed its size. Can you please check it once. @DeepanshiD  Mam , @vaishali614  Mam

2021-04-03 05:30 UTC, sonalisonawane commented
This one is new image :)
![banner](https://user-images.githubusercontent.com/66239376/113469486-23a6f100-93e1-11eb-82bf-933b6c265d4d.gif)

2021-04-03 09:28 UTC, vaishali614 requested changes

2021-04-03 09:28 UTC, vaishali614 commented on src/CSS/Banner.module.css
>    height: 400px;
Increase height to 550px
Add margin-top: -15%

And remove bottom padding from jumbotron to cut extra space above 'About Us' section.

Rest everything looks good.

2021-04-03 09:56 UTC, merged

2021-04-03 14:16 UTC, Manvityagi commented
Awesome work @sonalisonawane