(Feature/Styling) Opportunity Card Updated
Girl-Code-It/Opportunity-Calendar-Frontend pull request #201
Opened 2021-04-09 11:05 UTC by mohitms007

# Description
Redesign of the job/opportunity card and make it complement the whole website.  Make the card more intutive and easy to see.

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
I have only made changes to files needed for it that were opporutunity card and its styles. Rest are as it is. I have made the card more visible, fixed the image layout, added some classes and button props and make it visually appealing.

Fixed #194 

## Type of change
Visual Change/ Layout / UI design
Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-04-10 18:22 UTC, DeepanshiD commented
@mohitms007 Looks nice to me can you keep Apply button on the right bottom of card?
CC: @abdus

2021-04-11 02:40 UTC, mohitms007 commented
> @mohitms007 Looks nice to me can you keep Apply button on the right bottom of card?
> Increase shadow a bit on hover, not much just a little.
> Remove top blue bar
> 
> CC: @abdus 

Sure! Will fix it immediately.

2021-04-11 10:09 UTC, mohitms007 commented
> @mohitms007 Looks nice to me can you keep Apply button on the right bottom of card?
> Increase shadow a bit on hover, not much just a little.
> Remove top blue bar
> 
> CC: @abdus

Fixed it.

2021-04-11 15:21 UTC, vaishali614 requested changes

2021-04-11 15:21 UTC, vaishali614 commented on src/Components/ViewOpportunity/Opportunity.module.css
>    /* margin-left: 50%; */
Increase card width to 60rem and decrease margin-left to 5rem.

2021-04-11 15:21 UTC, vaishali614 commented on src/Components/ViewOpportunity/Opportunity.module.css
>  .CardImage {
Align the company logo with the heading on its right.

2021-04-11 15:21 UTC, vaishali614 commented on src/Components/ViewOpportunity/Opportunity.module.css
>    font-size: 20px;
Change font-size to 1.5rem

2021-04-11 15:21 UTC, vaishali614 commented on src/Components/ViewOpportunity/Opportunity.module.css
> +  margin-left: 10px;
Give it a font-size of 1.2rem

2021-04-11 15:21 UTC, vaishali614 commented on src/Components/ViewOpportunity/Opportunity.module.css
> +  font-size: 15px;
1. Change font-size to 1.2rem
2. Add padding: 5px 35px;
3. Add border: 1px solid #008CD8

2021-04-12 20:20 UTC, vaishali614 commented on src/Components/ViewOpportunity/Opportunity.module.css
>  .CardImage {
Logo still doesn't seem aligned with heading.

2021-04-13 05:44 UTC, mohitms007 commented on src/Components/ViewOpportunity/Opportunity.module.css
>  .CardImage {
The subtitle of the heading is causing issues with the alignment so I placed the subtitle to the right and aligned items in the center. Also tried to fix card issues and responsiveness of them by changing widths and font size of certain titles.

2021-04-13 06:30 UTC, vaishali614 commented on src/Components/ViewOpportunity/Opportunity.module.css
>  .CardImage {
I don't think that should be a problem. You can do it this way - 
1. One row: Two columns
2. First column: Image
3. Second column: Title and Subtitle

This should automatically align them

2021-04-13 06:49 UTC, mohitms007 commented on src/Components/ViewOpportunity/Opportunity.module.css
>  .CardImage {
I did the same in my first commit but still was not aligned properly probably due to some extra margins or padding. Is the company name(subtitle)  on right not suitable?

2021-04-13 06:53 UTC, vaishali614 commented on src/Components/ViewOpportunity/Opportunity.module.css
>  .CardImage {
Yeah it doesn't look good on right.
Try removing the extra margin/padding. If you're still unable to do so, undo the last changes i.e. subtitle on right and push the other changes.

2021-04-13 06:55 UTC, mohitms007 commented on src/Components/ViewOpportunity/Opportunity.module.css
>  .CardImage {
Alright! Will Try.

2021-04-13 08:28 UTC, mohitms007 commented on src/Components/ViewOpportunity/Opportunity.module.css
>  .CardImage {
I have pushed my changes. Placed the subtitle where it was and tried to cancel all margins and align them properly. Also checked up on the mobile versions aswell.

2021-04-13 11:59 UTC, vaishali614 commented on src/Components/ViewOpportunity/Opportunity.module.css
>  .CardImage {
okay

2021-04-13 11:59 UTC, vaishali614 commented
@mohitms007 Cards are not visible completely in small screens. Please check this thing. Rest seems good.

2021-04-13 13:54 UTC, mohitms007 commented
> @mohitms007 Cards are not visible completely in small screens. Please check this thing. Rest seems good.
> 
> ![4Capture](https://user-images.githubusercontent.com/32364768/114548806-e0207280-9c7d-11eb-9b14-d675b7628c5b.PNG)

Fixed it.

2021-04-13 19:05 UTC, vaishali614 commented
@mohitms007 That's the problem with some other screen sizes too. Please check for all screens before you update your PR.
Also, do take latest pull from upstream.

2021-04-14 04:37 UTC, mohitms007 commented
> @mohitms007 That's the problem with some other screen sizes too. Please check for all screens before you update your PR.
> Also, do take latest pull from upstream. Rest everything seems fine. Please update these changes so that I can merge your PR.

Checked all the screens works fine now

2021-04-15 06:36 UTC, vaishali614 approved these changes

2021-04-15 06:37 UTC, merged