View Opportunity Page revamp(#164)
Girl-Code-It/Opportunity-Calendar-Frontend pull request #203
Opened 2021-04-09 19:19 UTC by akshitakanojia

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed #164 

## Type of change

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2021-04-11 10:49 UTC, vaishali614 commented
@akshitakanojia Your changes don't match with the design. Please try to replicate exactly the same.

Some major visible corrections required -
1. While the opportunities are loading, there should be loader visible or you can keep it the same way it was before i.e. Looking for opportunities if any. (Please check the deployment for more clarity) 
2. Dropdown
3. Cards

2021-04-12 20:11 UTC, vaishali614 commented
@akshitakanojia Everything looks good, but please modify navbar too as per design.

2021-04-13 07:28 UTC, vaishali614 requested changes

2021-04-13 07:28 UTC, vaishali614 commented on src/Components/ViewOpportunity/Navbar.js
>  import React from 'react';
Please modify Navbar too according to design. Rest of the things look good.

2021-04-15 06:47 UTC, vaishali614 approved these changes

2021-04-15 06:48 UTC, vaishali614 commented
@akshitakanojia Changes look good now. Please take the latest pull from upstream to get this PR merged.

2021-04-15 17:26 UTC, akshitakanojia commented
@vaishali614 I'm getting merge conflicts while rebasing though I've already solved merge conflicts here.

2021-04-15 19:22 UTC, merged