Updated the responsiveness of the website
Girl-Code-It/Opportunity-Calendar-Frontend pull request #209
Opened 2021-04-13 03:45 UTC by Avishake007

# Description

Here I have updated the responsiveness the website
Fixed #192 

## Type of change

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)

# Checklist:

- [x] I have pulled the latest changes in the repository
- [ ] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-04-13 06:39 UTC, vaishali614 commented
@Avishake007 The Know About cards are in center in mobile screen but the changes you made shifted it to left in desktop screen. Please check that. Also, you've changed styles of a few sections. Please undo those changes.

2021-04-13 07:23 UTC, vaishali614 requested changes

2021-04-13 07:23 UTC, vaishali614 commented on src/CSS/KnowAboutCard.module.css
> +  /* box-shadow: 0px 3px 4px 0px #ccc; */
Undo this change

2021-04-13 07:23 UTC, vaishali614 commented on src/CSS/KnowAboutCard.module.css
> +  box-shadow: 0px 3px 4px 0px #ccc;
Undo this change

2021-04-13 07:23 UTC, vaishali614 commented on src/Components/HomePage/Sections/KnowAbout.js
> +            className={styles.justify_content}
This change has centered cards in mobile view but left aligned them in desktop view. Please check.

2021-04-13 19:13 UTC, vaishali614 approved these changes

2021-04-13 19:13 UTC, vaishali614 commented
@Avishake007 Changes look good. Please take the latest pull and update your PR, so that I can merge it.

2021-04-15 06:40 UTC, vaishali614 commented
> @Avishake007 Changes look good. Please take the latest pull and update your PR, so that I can merge it.

Reminder

2021-04-15 06:55 UTC, Avishake007 commented
Could you please explain me in details what I have to do?

2021-04-15 19:23 UTC, vaishali614 commented
> @vaishali614 Could you please explain me in details what I have to do?

You need to take the latest pull from upstream by running the following commands:
$ git pull upstream develop
$ git push origin develop

2021-04-16 03:15 UTC, Avishake007 commented
@vaishali614  Its done

2021-04-16 05:53 UTC, vaishali614 commented
> @vaishali614 Its done

Your fork is still 26 commits behind. Please check again.

2021-04-17 12:43 UTC, merged