forget password page
Girl-Code-It/Opportunity-Calendar-Frontend pull request #220
Opened 2021-04-17 17:13 UTC by kumarishalini6

# Description

I have made a forget password page and add navbar in the top.
 Fixed #217

## Type of change

![Opportunity Calendar - Personal - Microsoft​ Edge 4_17_2021 10_36_24 PM](https://user-images.githubusercontent.com/69043944/115121033-10f1f780-9f5d-11eb-9b2c-e4bf5ad37fcc.png)
![Opportunity Calendar - Personal - Microsoft​ Edge 4_17_2021 10_37_00 PM](https://user-images.githubusercontent.com/69043944/115121042-194a3280-9f5d-11eb-9bd4-69beabff6ec4.png)

2021-04-19 13:09 UTC, vaishali614 requested changes
@kumarishalini6 There are a few things to be changed -
1. The card looks too big, please keep it of same size as that of signup and login page.
2. Please add an image following the color scheme of the website.
3. There shouldn't be a 'Sign in with Google' button on a Forget password page.

2021-04-19 13:18 UTC, kumarishalini6 commented
Ok I'll do that

2021-04-19 13:37 UTC, kumarishalini6 commented
now the size and image are 
![Opportunity Calendar - Personal - Microsoft​ Edge 4_19_2021 07_02_29 PM](https://user-images.githubusercontent.com/69043944/115245389-58999000-a0d1-11eb-8841-8a1f25386c68.png)
ok?

2021-04-19 13:41 UTC, kumarishalini6 commented
![Opportunity Calendar - Personal - Microsoft​ Edge 4_19_2021 07_10_23 PM](https://user-images.githubusercontent.com/69043944/115245939-eaa19880-a0d1-11eb-83f5-f0313baab599.png)

2021-04-20 17:55 UTC, kumarishalini6 commented
please review this PR. I want t work on another issue.

2021-04-20 18:23 UTC, vaishali614 commented
> now the size and image are
> ![Opportunity Calendar - Personal - Microsoft​ Edge 4_19_2021 07_02_29 PM](https://user-images.githubusercontent.com/69043944/115245389-58999000-a0d1-11eb-8841-8a1f25386c68.png)
> ok?

The image still doesn't follow the color scheme of website. We're using #008DC8. Please update the image with this color code.
Rest of the things look fine.

2021-04-21 02:04 UTC, kumarishalini6 commented
ok

2021-04-21 02:14 UTC, kumarishalini6 commented
what about this image
![man-forgot-password-concept-computer-unhappy-businessman-near-computer-forgot-account-login-password-vector-male-character-158893967](https://user-images.githubusercontent.com/69043944/115486959-2b99ca00-a204-11eb-9275-18fecd25f905.jpg)

2021-04-21 02:23 UTC, kumarishalini6 commented
I guess this one is follow the website color.

2021-04-21 13:49 UTC, vaishali614 commented
@kumarishalini6 Please use the color code #008DC8 to verify the color.

2021-04-22 06:33 UTC, kumarishalini6 commented
I have exam in this week after that I'll work.

2021-04-25 05:27 UTC, kumarishalini6 commented
![self-service-password-reset-user-icon-png-favpng-5xmkeEBYK8s4fUXss089AbqcS](https://user-images.githubusercontent.com/69043944/115981910-c0bdfb00-a543-11eb-80dd-c8182a8190c2.jpg)
![#008dc8 - Google Search - Google Chrome 4_25_2021 10_54_55 AM](https://user-images.githubusercontent.com/69043944/115981919-c7e50900-a543-11eb-9b91-67936461c95d.png)
![13_Laptop_reset_password_password-512](https://user-images.githubusercontent.com/69043944/115981928-d7645200-a543-11eb-80c3-b7fee2f38ef4.png)

2021-04-25 05:31 UTC, kumarishalini6 commented
please check this images .

2021-04-25 11:28 UTC, ViVa98 commented
![Forgot password-rafiki](https://user-images.githubusercontent.com/35100223/115991611-f4059600-a5e6-11eb-8c31-d2e77df28cbc.png)

![Forgot password-bro](https://user-images.githubusercontent.com/35100223/115991714-5eb6d180-a5e7-11eb-838d-cb1fc570a0d4.png)

![Forgot password-pana](https://user-images.githubusercontent.com/35100223/115991658-2c0cd900-a5e7-11eb-8b85-760a5e21a42c.png)


 add the text "Illustration by Freepik Storyset" in alt or somewhere.

2021-04-25 11:37 UTC, kumarishalini6 commented
Can I ask you something?
How didi you change the color ??
And I'll change the text

2021-04-25 11:47 UTC, ViVa98 commented
I think you got those previous images from a direct google search. When I saw the image used I thought that the image is shown from "freepik" as I use mostly as my design resources. Once you select any image wanting to use, there is an edit option that redirects you to the online editor where you can edit a particular image.

2021-04-25 11:49 UTC, kumarishalini6 commented
Thanks , I didn't know about it , now it helps me a lot thanks once again

2021-04-25 13:22 UTC, kumarishalini6 commented
Now check the PR

2021-04-25 13:24 UTC, kumarishalini6 commented
![Opportunity Calendar - Personal - Microsoft​ Edge 4_25_2021 06_31_58 PM](https://user-images.githubusercontent.com/69043944/115995117-7611a280-a586-11eb-8d61-468f2b73c45e.png)

2021-04-26 11:09 UTC, vaishali614 commented
Image is perfect now. But the form seems too big as compared to the login/signup forms. Please refer the images below - 

![Screenshot (428)](https://user-images.githubusercontent.com/32364768/116073245-c6375480-a6ad-11eb-9d1d-a999415be1ee.png)
![Screenshot (429)](https://user-images.githubusercontent.com/32364768/116073254-c8011800-a6ad-11eb-9b15-c5523fa1b8ac.png)

I think padding of input fields can be reduced and do check for the font-sizes. Also, please change the heading to 'Forgot Password' instead of 'Forget Password'.

Rest everything seems good.

2021-04-26 11:20 UTC, vaishali614 requested changes

2021-04-26 11:20 UTC, vaishali614 commented on src/Components/SignupLogin/Login.js
> -    <div>
@kumarishalini6 Why have you edited this file and removed Navbar? Please make sure to not edit a file which is not concerned with the assigned issue.

2021-04-26 11:22 UTC, vaishali614 commented
Also, I noticed that your changes have changed the color of our homepage banner.

![Capture](https://user-images.githubusercontent.com/32364768/116074725-c0db0980-a6af-11eb-9256-6ce751d6fb2d.PNG)

This is the original color:
![Capture2](https://user-images.githubusercontent.com/32364768/116074753-cafd0800-a6af-11eb-846f-2d19802e9b08.PNG)

Please check and revert any such change.

2021-04-26 13:14 UTC, kumarishalini6 commented
Sorry about sign in page it happens by mistake
and i have done all the changes 
![Opportunity Calendar - Personal - Microsoft​ Edge 4_26_2021 06_40_07 PM](https://user-images.githubusercontent.com/69043944/116088284-331b0200-a64e-11eb-8e12-9231fdfb1598.png)

2021-05-01 08:34 UTC, Manvityagi approved these changes

2021-05-02 11:02 UTC, vaishali614 approved these changes

2021-05-02 11:04 UTC, vaishali614 commented
@kumarishalini6 Changes look good now, but please take the latest pull from upstream whenever you update your PR. Your fork is 28 commits behind. Please take the latest pull and update your PR to get it merged.

2021-05-02 11:31 UTC, kumarishalini6 commented
ok

2021-05-02 11:41 UTC, kumarishalini6 commented
Done

2021-05-02 11:43 UTC, kumarishalini6 commented
@vaishali614 also assign me the another issue that i have created

2021-05-02 12:06 UTC, merged