View opportunity api changes done (#228)
Girl-Code-It/Opportunity-Calendar-Frontend pull request #230
Opened 2021-04-21 12:08 UTC by akshitakanojia

# Description

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.

Fixed #228 

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-04-21 14:03 UTC, vaishali614 requested changes
Good work @akshitakanojia. There are few minor changes -

1. There's another field opportunityOrganisation in JOBS and INTERNSHIP. Please use that for company name. You can use this [Swagger Doc](opportunityOrganisation) to verify fields for all opportunities.
2.  Display date in this format: YYYY-MM-DD or DD-MM-YYYY

2021-04-21 14:59 UTC, akshitakanojia commented
> Good work @akshitakanojia. There are few minor changes -
> 
> 1. There's another field opportunityOrganisation in JOBS and INTERNSHIP. Please use that for company name. You can use this [Swagger Doc](opportunityOrganisation) to verify fields for all opportunities.
> 2. Display date in this format: YYYY-MM-DD or DD-MM-YYYY

@vaishali614  I'm not able to access the link for swagger doc . Can you please check and tell the correct link.

2021-04-21 15:22 UTC, vaishali614 commented
> > Good work @akshitakanojia. There are few minor changes -
> > 
> > 1. There's another field opportunityOrganisation in JOBS and INTERNSHIP. Please use that for company name. You can use this [Swagger Doc](opportunityOrganisation) to verify fields for all opportunities.
> > 2. Display date in this format: YYYY-MM-DD or DD-MM-YYYY
> 
> @vaishali614 I'm not able to access the link for swagger doc . Can you please check and tell the correct link.

Please use this link: https://opportunity-calendar.herokuapp.com/playground/#/default/get_opportunity

2021-04-24 09:34 UTC, vaishali614 approved these changes

2021-04-24 09:34 UTC, merged