Updated api to create new opportunity
Girl-Code-It/Opportunity-Calendar-Frontend pull request #233
Opened 2021-04-22 06:37 UTC by Samridhi-98

# Description

Updated API in all sections of the post opportunity and code refactoring.

Fixed #229 

## Type of change

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [x] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-04-22 06:38 UTC, Samridhi-98 commented
@vaishali614  @Manvityagi  Please review my PR.

2021-04-24 09:57 UTC, vaishali614 commented
> @vaishali614 @Manvityagi Please review my PR. Also, there is no field for opportunityImage in the mongoose schema but the form section has the state property for the image. Should I remove it from the frontend part or simply open an issue in the backend repository to update the opportunity schema.

Please open an issue in backend repo. Other than that, your changes look good. When the field for image is added, please update your PR. Also, do take the latest pull from upstream before you update your PR.

2021-04-24 13:21 UTC, Manvityagi commented
> @vaishali614 @Manvityagi Please review my PR. Also, there is no field for opportunityImage in the mongoose schema but the form section has the state property for the image. Should I remove it from the frontend part or simply open an issue in the backend repository to update the opportunity schema.

https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/issues/65 
Have opened the issue in backend for the same

2021-04-24 13:55 UTC, Samridhi-98 commented
> > @vaishali614 @Manvityagi Please review my PR. Also, there is no field for opportunityImage in the mongoose schema but the form section has the state property for the image. Should I remove it from the frontend part or simply open an issue in the backend repository to update the opportunity schema.
> 
> [Girl-Code-It/Opportunity-Calendar-Backend#65](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/issues/65)
> Have opened the issue in backend for the same

Thank you, Will update this PR as soon as that PR will be merged, till the time I am keeping it as a draft PR.

2021-04-24 14:15 UTC, Manvityagi commented
> > > @vaishali614 @Manvityagi Please review my PR. Also, there is no field for opportunityImage in the mongoose schema but the form section has the state property for the image. Should I remove it from the frontend part or simply open an issue in the backend repository to update the opportunity schema.
> > 
> > 
> > [Girl-Code-It/Opportunity-Calendar-Backend#65](https://github.com/Girl-Code-It/Opportunity-Calendar-Backend/issues/65)
> > Have opened the issue in backend for the same
> 
> Thank you, Will update this PR as soon as that PR will be merged, till the time I am keeping it as a draft PR.

Sounds good 👍

2021-05-02 06:56 UTC, Samridhi-98 commented
@vaishali614  @Manvityagi  I have updated for image URL please review.

2021-05-02 10:42 UTC, vaishali614 commented
> @vaishali614 @Manvityagi I have updated for image URL please review.

I can't post an opportunity.
![Screenshot (10)](https://user-images.githubusercontent.com/32364768/116805962-b1444080-ab47-11eb-9f3e-f70f73089dfe.png)

2021-05-02 11:23 UTC, Samridhi-98 commented
> > @vaishali614 @Manvityagi I have updated for image URL please review.
> 
> @Samridhi-98 I can't post an opportunity.
> ![Screenshot (10)](https://user-images.githubusercontent.com/32364768/116805962-b1444080-ab47-11eb-9f3e-f70f73089dfe.png)
> 
> CC: @Manvityagi

@vaishali614 I am not sure but there is some error at the backend while testing the URL I am not able to retrieve anything, got this error message please let me know how can I fix this.

**Screenshot**
![frontend](https://user-images.githubusercontent.com/54466041/116811437-e4e29300-ab66-11eb-8394-276864b4973b.JPG)

2021-05-02 11:49 UTC, Manvityagi commented
> > > @vaishali614 @Manvityagi I have updated for image URL please review.
> > 
> > 
> > @Samridhi-98 I can't post an opportunity.
> > ![Screenshot (10)](https://user-images.githubusercontent.com/32364768/116805962-b1444080-ab47-11eb-9f3e-f70f73089dfe.png)
> > CC: @Manvityagi
> 
> @vaishali614 I am not sure but there is some error at the backend while testing the URL I am not able to retrieve anything, got this error message please let me know how can I fix this.
> 
> **Screenshot**
> ![frontend](https://user-images.githubusercontent.com/54466041/116811437-e4e29300-ab66-11eb-8394-276864b4973b.JPG)

It should be working now, Please check

2021-05-02 12:03 UTC, Samridhi-98 commented
> > > > @vaishali614 @Manvityagi I have updated for image URL please review.
> > > 
> > > 
> > > @Samridhi-98 I can't post an opportunity.
> > > ![Screenshot (10)](https://user-images.githubusercontent.com/32364768/116805962-b1444080-ab47-11eb-9f3e-f70f73089dfe.png)
> > > CC: @Manvityagi
> > 
> > 
> > @vaishali614 I am not sure but there is some error at the backend while testing the URL I am not able to retrieve anything, got this error message please let me know how can I fix this.
> > **Screenshot**
> > ![frontend](https://user-images.githubusercontent.com/54466041/116811437-e4e29300-ab66-11eb-8394-276864b4973b.JPG)
> 
> It should be working now, Please check

Yes, It's working.

2021-05-02 13:08 UTC, vaishali614 commented
@Samridhi-98 The changes look perfect. But, we've added two more fields in the schema: opportunityType, onlyForFemale.
Since you've been working on the opportunity form, can you add a dropdown for opportunityType with values JOB, INTERNSHIP, HACKATHON, SCHOLARSHIP, CONFERENCE, CODINGCOMPETITION and a toggle button for onlyForFemale in the form for these two fields? 
Apart from this, everything looks good.

2021-05-02 13:12 UTC, Manvityagi commented
> @Samridhi-98 The changes look perfect. But, we've added two more fields in the schema: opportunityType, onlyForFemale.
> Since you've been working on the opportunity form, can you add a dropdown for opportunityType with values JOB, INTERNSHIP, HACKATHON, SCHOLARSHIP, CONFERENCE, CODINGCOMPETITION and a toggle button for onlyForFemale in the form for these two fields?
> Apart from this, everything looks good.
> 
> You can refer to the Swagger Doc [here](https://opportunity-calendar.herokuapp.com/playground/#/default/post_opportunity)

I think we can increase the level of this issue from 2 to 3, if you want to take this added task.

2021-05-02 13:22 UTC, Samridhi-98 commented
> @Samridhi-98 The changes look perfect. But, we've added two more fields in the schema: opportunityType, onlyForFemale.
> Since you've been working on the opportunity form, can you add a dropdown for opportunityType with values JOB, INTERNSHIP, HACKATHON, SCHOLARSHIP, CONFERENCE, CODINGCOMPETITION and a toggle button for onlyForFemale in the form for these two fields?
> Apart from this, everything looks good.
> 
> You can refer to the Swagger Doc [here](https://opportunity-calendar.herokuapp.com/playground/#/default/post_opportunity)

Sure, I will add it.

2021-05-02 18:20 UTC, Samridhi-98 commented
@vaishali614 Do I need to add a dropdown for opportunityType in each form, Since each and every opportunity type has its own separate form so it's pointless to add opportunityType dropdown.

2021-05-02 19:22 UTC, vaishali614 commented
> @vaishali614 Do I need to add a dropdown for opportunityType in each form, Since each and every opportunity type has its own separate form so it's pointless to add opportunityType dropdown.

Yeah I agree with you, but we're planning to reduce 6 forms into 1 form, so we'll need the dropdown. But for now, we need this dropdown in each form.

2021-05-03 03:35 UTC, Samridhi-98 commented
> > @vaishali614 Do I need to add a dropdown for opportunityType in each form, Since each and every opportunity type has its own separate form so it's pointless to add opportunityType dropdown.
> 
> Yeah I agree with you, that's why we're planning to reduce 6 forms into 1 form, so we'll need the dropdown. But for now, just add this dropdown in each form.

Okay.

2021-05-03 08:21 UTC, Samridhi-98 commented
@vaishali614  @Manvityagi  Please review.

2021-05-07 08:20 UTC, vaishali614 commented
1. You are using the same ID twice on the same page
2. There's some error on your end while making request. Please check.

![Screenshot (53)](https://user-images.githubusercontent.com/32364768/117419968-c3a0ee80-af3a-11eb-8a87-9d8764930f71.png)

2021-05-08 09:19 UTC, Samridhi-98 commented
> 1. You are using the same ID twice on the same page
> 2. There's some error on your end while making request. Please check.
> 
> ![Screenshot (53)](https://user-images.githubusercontent.com/32364768/117419968-c3a0ee80-af3a-11eb-8a87-9d8764930f71.png)
> 
> PS: Please make sure you test it completely before you update your PR for review.

@vaishali614  I am unable to send the request will you please help me out with this.

**Screeenshot**

![main](https://user-images.githubusercontent.com/54466041/117533810-68d7c780-b00c-11eb-8246-c20eb18e8463.JPG)

![ex1](https://user-images.githubusercontent.com/54466041/117535106-cfabaf80-b011-11eb-9c75-f8f428264437.JPG)

![ex2](https://user-images.githubusercontent.com/54466041/117535107-d1757300-b011-11eb-9364-e96b536989d9.JPG)

2021-05-08 15:13 UTC, vaishali614 requested changes
- Please make sure these changes are done for all the forms.
- Do check the Swagger Doc to confirm the field names in case any errors are encountered.

2021-05-08 15:13 UTC, vaishali614 commented on src/Components/PostOpportunity/sections/FullTime/FullTimeForm.js
> +          opportunityOnlyForFemale: this.state.onlyForFemale,
The field is 'onlyForFemale' not 'opportunityOnlyForFemale', 'opportunityId' field has been removed and there's one more field 'opportunityDate'.

opportunityDate can be same as deadline for jobs, internships, scholarships, but for others there should be a different input field.

2021-05-08 15:13 UTC, vaishali614 commented on src/Components/PostOpportunity/sections/FullTime/FullTimeForm.js
> +                    defaultValue="Type"
Add 
name="type"
value={type}

2021-05-08 15:13 UTC, vaishali614 commented on src/Components/PostOpportunity/sections/FullTime/FullTimeForm.js
> +                    <option value="Internship">Internship</option>
values should be JOB, INTERNSHIP, HACKATHON, SCHOLARSHIP, CONFERENCE, CODINGCOMPETITION

2021-05-09 08:19 UTC, Samridhi-98 commented
@vaishali614  I have updated as you suggested and each form is properly working please review and let me know if anything else to update.

2021-05-09 11:18 UTC, vaishali614 approved these changes

2021-05-09 11:18 UTC, merged