hover effect on opportunity box
Girl-Code-It/Opportunity-Calendar-Frontend pull request #252
Opened 2021-05-12 08:05 UTC by kumarishalini6

fixes#issue-249

Please include a summary of the change and which issue is fixed. List any dependencies that are required for this change.
I have gave some background color , border color and hover effect.
![Opportunity Calendar - Personal - Microsoft​ Edge 5_12_2021 01_29_15 PM](https://user-images.githubusercontent.com/69043944/117940575-aca12a00-b2b5-11eb-8d4e-2c080e11c682.png)

2021-05-12 08:06 UTC, kumarishalini6 commented
video:-

https://user-images.githubusercontent.com/69043944/117940763-e07c4f80-b2b5-11eb-84e6-37f351d8f16b.mp4

2021-05-12 20:40 UTC, vaishali614 requested changes

2021-05-12 20:40 UTC, vaishali614 commented on src/CSS/Opportunity.module.css
> +    transform: scale(1.2);
Change it to transform: scale(1.05);

2021-05-12 20:40 UTC, vaishali614 commented on src/CSS/Opportunity.module.css
> +    border-color: gray;
Remove border-color

2021-05-13 05:30 UTC, kumarishalini6 commented on src/CSS/Opportunity.module.css
> +    transform: scale(1.2);
Ok

2021-05-13 05:30 UTC, kumarishalini6 commented on src/CSS/Opportunity.module.css
> +    border-color: gray;
Ok

2021-05-13 05:36 UTC, kumarishalini6 commented
done

2021-05-13 12:35 UTC, merged