Combine multiple Post Opportunity Forms into One form #254
Girl-Code-It/Opportunity-Calendar-Frontend pull request #261
Opened 2021-05-21 13:50 UTC by AyushPradhan9

# Description
Changes made:
1) Deleted the specific form from every sections in src/Components/PostOpportunity/sections/..
2) Created one generic form in src/Components/PostOpportunity/sections/OpportunityForm

Fixed #254 

## Type of change

Please check options that are relevant to your PR.

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [x] I have pulled the latest changes in the repository
- [x] I have squashed my commits
- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings

2021-05-22 19:37 UTC, vaishali614 requested changes
@AyushPradhan9 It looks perfect now. Just one more thing, can you redirect it to the respective view opportunity page on form submission?

2021-05-23 10:02 UTC, vaishali614 commented
@AyushPradhan9 The opportunities are not posted on submit. It's only redirected to view opportunity page. Ideally, it should submit first and then redirect to the view opportunity page. If you're unable to do so, leave it as it was. Don't redirect, but the form must be submitted correctly.

2021-05-23 10:07 UTC, AyushPradhan9 commented
Apologizes, I thought I did the thing right and in a hurry forgot to check whether jobs are being posted or not. Surely will report a PR by tonight if I am able to do the redirect, else will report PR without it. Thank you!

2021-05-23 18:23 UTC, vaishali614 approved these changes

2021-05-23 18:23 UTC, merged