Added newsletter
Girl-Code-It/Opportunity-Calendar-Frontend pull request #267
Opened 2021-05-25 07:19 UTC by sandra9711

# Description

Added a component for newsletter with link in products part of footer

Fixed #263 

## Type of change

Please check options that are relevant to your PR.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] This change requires a documentation update

# Checklist:

- [ ] I have pulled the latest changes in the repository
- [ ] I have squashed my commits
- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings

2021-06-01 07:26 UTC, vaishali614 commented
@sandra9711 Apologies for the delay. 
We don't want a separate page for subscribing to our newsletter, instead you can just add an input field with a button to Subscribe, like [here](https://seekho.ai/academy/product-management).
Also, Newsletter is not a Product, so remove it from there and simply add this input field above "Get in Touch" section.

2021-06-01 11:50 UTC, sandra9711 commented
@vaishali614 
Made all changes mentioned

2021-06-02 05:48 UTC, vaishali614 commented
> @vaishali614
> Made all changes mentioned

It's not in center, please keep it aligned with other components. Other than that, it looks good to go.
![Screenshot (158)](https://user-images.githubusercontent.com/32364768/120430092-1d5ad400-c394-11eb-81ea-da68b17b989a.png)

2021-06-02 17:29 UTC, sandra9711 commented
@vaishali614 

I corrected the alignment as in this picture

![oc3](https://user-images.githubusercontent.com/66560251/120525390-b79f3400-c3f5-11eb-9791-308f7fc5f8d5.png)

But it looks like this in the deploy preview

![oc4](https://user-images.githubusercontent.com/66560251/120525570-e1585b00-c3f5-11eb-91fd-646a70211aa0.png)

2021-06-02 19:50 UTC, vaishali614 approved these changes

2021-06-02 19:54 UTC, vaishali614 requested changes

2021-06-02 19:54 UTC, vaishali614 commented on src/App.js
> +          <Route path="/newsletter" component={Newsletter} strict exact/>
This is not required now

2021-06-02 19:54 UTC, vaishali614 commented on src/CSS/Newsletter.module.css
> +
Please remove unnecessary code from this file

2021-06-02 19:54 UTC, vaishali614 commented on src/Components/HomePage/Sections/Navbar.js
> +          <Link smooth={true} offset={-90} duration={1000} to="faqs">
Remove it from navbar too

2021-06-03 19:13 UTC, vaishali614 requested changes

2021-06-03 19:13 UTC, vaishali614 commented on src/Assets/subscribe.svg
> +<svg xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" id="Layer_1" x="0px" y="0px" viewBox="0 0 1080 1080" enable-background="new 0 0 1080 1080" xml:space="
Why is this svg file added? I don't see it getting used anywhere. Please remove this if it's unnecessary.

2021-06-04 05:56 UTC, vaishali614 approved these changes

2021-06-04 05:56 UTC, merged