issueno32
Girl-Code-It/Opportunity-Calendar-Frontend pull request #39
Opened 2021-03-09 11:55 UTC by saumyasrivastava08

Fixed #32

2021-03-09 13:58 UTC, Manvityagi requested changes
@saumyasrivastava08 
You probably didn't pull the latest code, The code has been refactored with a PR which was merged earlier in the day, 
There are no files like these now:
src/Components/ViewOpportunity/Sections/FullTime/FullTime.js   

Please pull the latest code and do the changes to it. 

Overall, The changes that you have made are good.

2021-03-09 16:47 UTC, saumyasrivastava08 commented
@Manvityagi how to do that

2021-03-09 17:00 UTC, Manvityagi commented
> @Manvityagi how to do that

# add upstream
$ git remote add upstream https://github.com/Girl-Code-It/Opportunity-Calendar-Frontend

# include all the latest changes from the remote repository
$ git fetch upstream
$ git merge upstream/develop

2021-03-10 04:16 UTC, abdus requested changes

2021-03-10 04:16 UTC, abdus commented on package.json
> +    "@material-ui/icons": "^4.11.2",
we already have a UI framework (`react-bootstrap`). I don't see a need for adding `@material-ui/core`

2021-03-10 04:16 UTC, abdus commented on src/Components/ViewOpportunity/Sections/Dropdown/dropdown.js
> +import Fade from '@material-ui/core/Fade';
please check this out https://react-bootstrap.github.io/components/dropdowns/

2021-03-10 04:16 UTC, abdus commented on src/Components/ViewOpportunity/Sections/Navbar.js
> +import MoreIcon from '@material-ui/icons/MoreVert';
Please replace these with [`react-bootstrap`](https://react-bootstrap.github.io/components/)

2021-03-10 05:49 UTC, saumyasrivastava08 commented
@Manvityagi @abdus I will do the changes u told

2021-03-10 05:49 UTC, saumyasrivastava08 commented on src/Components/ViewOpportunity/Sections/Navbar.js
> +import MoreIcon from '@material-ui/icons/MoreVert';
Sure

2021-03-10 08:01 UTC, saumyasrivastava08 commented
I have push the new changes but all the prechecks are failed

2021-03-10 08:44 UTC, abdus commented
@saumyasrivastava08, which pull request should I consider? this one(#39) or pull #46 ? It's a bit confusing as the pull request description you have provided is not clear. 
Please let me know.

2021-03-10 08:56 UTC, saumyasrivastava08 commented
@abdus  consider the previous one mobile tab view

2021-03-10 09:01 UTC, closed without merging